@startmindmap
* WEB3
**:Layer1:通信层
<code>
区块链数据安全地存储在数据服务器中。
当我们浏览网页或使用任何区块链应用程序时，
我们的机器会请求从服务器访问这些数据。
促进这种数据交换的框架称为客户端-服务器架构。

区块链是点对点 (P2P) 网络，允许客户端与
“点对点”连接，从而更快、更轻松地共享数据。
它只不过是一个庞大的设备网络，它们相互通信
并相互请求数据。这就是分布式账本的创建方式。
与网络上的另一个设备通信的每个设备都是一个节点。
每个节点随机验证交易数据。
</code>;
**:Layer2:数据层
<code>
区块链只不过是一长串包含交易数据的“块”。
当节点验证一定数量的交易时，数据被捆绑到
一个“块”中，添加到区块链中，并与前一个数据块链接。

“创世块”是链中的第一个块，
因此不需要与任何先前的块链接。
相反，后续块与创世块链接，并且每次添加
新块时都会重复该过程。这就是区块链的形成
和不断发展的方式。

每笔交易都使用发件人钱包的私钥进行“数字签名”。
只有发送者才能访问此密钥，从而确保数据不会被
其他任何人访问或篡改。
这在区块链术语中称为“最终性”。

数字签名还可以保护所有者的身份，
该身份本身是加密的，从而确保了最大的安全性。
</code>;
**:Layer3:网络层
<code>
P2P 框架使各个节点能够交换交易数据以就
交易的有效性达成共识。这意味着每个节点都
必须能够发现网络上的其他节点以进行快速通信。

正是网络层促进了这种“节点间通信”。
由于节点发现、块创建和块添加也由该
层管理，因此也称为“传播层”。
</code>;
**:Layer4:共识层
<code>
这是区块链操作中最关键的层。
这一层负责验证交易，没有它，整个系统都会失败。

该层运行需要一定数量的节点来验证一笔交易的协议。

因此，每笔交易都由多个节点处理，然后这些节点必须
达到相同的结果并就其有效性达成一致。

该框架保持了区块链的去中心化性质，因为没有节点可
以单独控制任何交易数据，并且角色是分布式的。
这称为共识机制。

由于有如此多的节点处理交易，将它们捆绑起来并将它们
添加到区块链中，因此可能会同时创建多个块，从而在区
块链中形成一个分支。

但是，必须始终存在单个链块添加，并且共识层也确保解决此冲突。
</code>;
**:Layer5:应用层
<code>
这是运行智能合约和去中心化应用程序 (dApp) 的层。
智能合约根据某些触发因素做出决策，例如合约到期日、
现货价格的实现等。遵循这些决策的行动由 dApp 执行，
而这一切都发生在应用层。

dApp还促进了用户设备和区块链之间的通信。
因此，应用程序就像面向用户的前端，而主区块链是后端，
数据安全地存储在其中。
</code>;
@endmindmap